version: '2'
services:
  mongodb:
    container_name: mongodb-sb
    image: mongo:4.0.0
    volumes:
    - mongodb-data:/data/db

  app:
    container_name: sb-sample
    build: .
    ports:
    - 8080:8080
    volumes:
    - ~/.m2:/root/.m2
    links:
    - mongodb:mongodb
    depends_on:
    - mongodb
    environment:
    - MONGODB_HOST=mongodb
    - MONGODB_PORT=27017
    - MONGODB_DATABSE=sample

volumes:
  mongodb-data:
    driver: local
