platform: linux

image_resource:
  type: docker-image
  source: {repository: java, tag: 8}

inputs:
  - name: sb-sample-service

outputs:
  - name: sb-sample-service

caches:
  - path: .m2/

run:
  path: "sb-sample-service/concourse/tasks/build.sh"