platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: latest}

inputs:
  - name: build-output

run:
  path: ls
  args: ["build-output"]
  #path: "sb-sample-service/concourse/tasks/test.sh"