platform: linux

image_resource:
  type: docker-image
  source: {repository: docker, tag: latest}

inputs:
  - name: target

run:
  path: ls
  args: ["-lR"]
  #path: "sb-sample-service/concourse/tasks/test.sh"