name: "E2E Test"
on: [workflow_dispatch]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: minikube start
    - name: Deploy to minikube
      run: kubectl apply -f manifest.yml
    - name: Wait
      run: sleep 60
    - name: Show deployment
      run: kubectl get po,deploy
