name: Java CI

on: [workflow_dispatch]

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: ./mvnw package

    - uses: actions/upload-artifact@master
      with:
        name: sb-sample-service.jar
        path: ./target/sb-sample-service.jar

  build-image:

    needs: package
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: sb-sample-service.jar
        path: ./target

    - name: Build image and Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: docker.pkg.github.com/kondoumh/sb-sample-service/app
        username: kondoumh
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
